name: CI/CD DevOps Final (.NET 9)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test-publish-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore HolaMundoApp/HolaMundoApp.csproj

    - name: Build
      run: dotnet build --no-restore -c Release HolaMundoApp/HolaMundoApp.csproj

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/holamundoapp:latest
        docker build -t "$IMAGE" .
        docker push "$IMAGE"

    - name: Trigger Render Deploy
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -fsSL -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys
